language: php

sudo: false
services:
  - mysql

php:
  - 7.0
  - 5.6

before_script:
  - mysql -e 'create database test;'
  - composer install -n

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi